### ISSUE TITLE
Change Font color for Icons to White instead of Red (Inverse Color)

### ISSUE THREAD

**Issue by kallyas** [Kabahindarovence13/kabahindarovence#1]
https://github.com/Kabahindarovence13/kabahindarovence/blob/aedacce5b289e9b1211634d05627f005b07004ca/css/colors.css#L567

```css
.aali_tm_all_wrap[data-color="red"] .aali_tm_copyright .social ul li a:hover {
background-color: #fe0000;
color: #ffffff;
} 
```

End Result on Hover
![image](https://user-images.githubusercontent.com/60466044/154451557-be68132b-3b27-4b25-b732-07e0e4e0b687.png)
